import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os

class ReportDraftAgent:
    """
    Agent 4: Analyze data from Agent 1. (for now)
    Responsible for generating visual charts and drafting the final report.
    """
    def __init__(self, output_dir: str = "reports"):
        self.agent_name = "ReportDraft"
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        sns.set_theme(style="darkgrid")

    def create_visualizations(self, data: dict) -> List[str]:
        """Generates charts and returns the file paths."""
        ticker = data['ticker']
        hist_data = data.get('historical_data', {})
        
        if not hist_data or "prices" not in hist_data:
            return []

        # Prepare DataFrame
        df = pd.DataFrame({
            'Date': pd.to_datetime(hist_data['dates']),
            'Close': hist_data['prices']['close']
        })

        file_paths = []
        
        # 1. Price Trend Chart
        plt.figure(figsize=(10, 5))
        plt.plot(df['Date'], df['Close'], label='Closing Price', color='#00aaff', linewidth=2)
        plt.title(f"{ticker} Price Trend (Last 30 Days)")
        plt.xlabel("Date")
        plt.ylabel("Price (USD)")
        plt.xticks(rotation=45)
        
        path = f"{self.output_dir}/{ticker}_trend.png"
        plt.tight_layout()
        plt.savefig(path)
        plt.close()
        file_paths.append(path)
        
        return file_paths

    def generate_report_draft(self, data: dict, market_insight: str = "") -> str:
        """
        Draft textual report. 
        pass data to LLM here
        """
        ticker = data['ticker']
        metrics = data.get('key_metrics', {})
        perf = data.get('historical_data', {}).get('summary', {})
        
        # Simple logic-based drafting (can be replaced by LLM prompt)
        status = "Bullish" if metrics.get('pe_ratio', 0) < 30 else "Premium Valuation"
        
        report = f"""
# INVESTMENT RESEARCH REPORT: {ticker}
**Generated by:** {self.agent_name}
---
## Executive Summary
{ticker} is currently trading at ${data['current_data']['current_price']}. 
Over the last 30 days, the stock has seen a return of {perf.get('total_return_percent', 0):.2f}%.

## Financial Health & Valuation
- **P/E Ratio:** {metrics.get('pe_ratio', 'N/A')} (Indicates {status})
- **Profit Margin:** {metrics.get('profit_margins', 'N/A')}%
- **Analyst Sentiment:** {data['analyst_recommendations'].get('recommendation_key', 'Hold')}

## Risk Assessment
The stock's beta of {metrics.get('beta', 'N/A')} suggests it is { 'more' if metrics.get('beta', 1) > 1 else 'less' } volatile than the broader market.
"""
        return report