from typing import List
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os


class ReportDraftAgent:
    """
    Agent 4: Analyze data from Agent 1.
    Responsible for generating visual charts and drafting the final report.
    """

    def __init__(self, output_dir: str = "reports"):
        self.agent_name = "ReportDraft"
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)
        sns.set_theme(style="darkgrid")

    def create_visualizations(self, data: dict) -> List[str]:
        """Generate charts and return their file paths."""
        ticker = data.get("ticker", "UNKNOWN")
        hist_data = data.get("historical_data", {})

        if not hist_data or "prices" not in hist_data or "dates" not in hist_data:
            return []

        prices = hist_data["prices"]
        if "close" not in prices:
            return []

        df = pd.DataFrame({
            "Date": pd.to_datetime(hist_data["dates"]),
            "Close": prices["close"],
        })

        if df.empty:
            return []

        file_paths = []

        plt.figure(figsize=(10, 5))
        plt.plot(df["Date"], df["Close"], label="Closing Price", linewidth=2)
        plt.title(f"{ticker} Price Trend (Last 30 Days)")
        plt.xlabel("Date")
        plt.ylabel("Price (USD)")
        plt.xticks(rotation=45)

        path = os.path.join(self.output_dir, f"{ticker}_trend.png")
        plt.tight_layout()
        plt.savefig(path)
        plt.close()

        file_paths.append(path)
        return file_paths

    def generate_report_draft(self, data: dict, market_insight: str = "") -> str:
        """
        Draft a textual report.
        """
        ticker = data.get("ticker", "UNKNOWN")
        metrics = data.get("key_metrics", {})
        perf = data.get("historical_data", {}).get("summary", {})
        current_data = data.get("current_data", {})
        analyst_recs = data.get("analyst_recommendations", {})

        pe_ratio = metrics.get("pe_ratio")
        beta = metrics.get("beta", "N/A")

        if isinstance(pe_ratio, (int, float)):
            status = "Bullish" if pe_ratio < 30 else "Premium Valuation"
        else:
            status = "Unknown"

        beta_text = "unknown"
        if isinstance(beta, (int, float)):
            beta_text = "more" if beta > 1 else "less"

        report = f"""
# INVESTMENT RESEARCH REPORT: {ticker}
**Generated by:** {self.agent_name}

---

## Executive Summary
{ticker} is currently trading at ${current_data.get('current_price', 'N/A')}.
Over the last 30 days, the stock has seen a return of {perf.get('total_return_percent', 0):.2f}%.

## Financial Health & Valuation
- **P/E Ratio:** {pe_ratio if pe_ratio is not None else 'N/A'} (Indicates {status})
- **Profit Margin:** {metrics.get('profit_margins', 'N/A')}%
- **Analyst Sentiment:** {analyst_recs.get('recommendation_key', 'Hold')}

## Risk Assessment
The stock's beta of {beta} suggests it is {beta_text} volatile than the broader market.

## Market Insight
{market_insight if market_insight else 'No additional market insight provided.'}
"""
        return report.strip()